---
- name: install nginx
  apt: name=nginx state=present update_cache=yes
  register: nginx_installed
  notify: start nginx

- name: remove default site from nginx sites-enabled
  when: nginx_installed|success
  register: nginx_default_site_disabled
  file: dest=/etc/nginx/sites-enabled/default state=absent

- name: copy nginx configuration
  when: nginx_installed|success
  register: nginx_config_copied
  template: src=default.conf dest=/etc/nginx/sites-available/robcutmore.com.conf

- name: setup nginx sites-enabled symlink
  when: nginx_default_site_disabled|success and nginx_config_copied|success
  file: path=/etc/nginx/sites-enabled/robcutmore.com.conf
        src=/etc/nginx/sites-available/robcutmore.com.conf
        state=link
        force=yes
  notify: reload nginx
