---
- name: start nginx
  become: yes
  become_method: sudo
  become_user: root
  service: name=nginx state=started enabled=yes

- name: reload nginx
  become: yes
  become_method: sudo
  become_user: root
  service: name=nginx state=reloaded
